##Exercise 1

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [1]:
#A.

import numpy as np

A = np.array([[i for i in range(1, 11)] for _ in range(10)])

print("A:\n", A)

print("Shape of A:", A.shape)

#np.array(): Creates a new ndarray object.
#[[i for i in range(1, 11)] for _ in range(10)]: Creates a nested Python list containing values from 1 to 100.
#A.shape: Returns the shape of the ndarray object A.

A:
 [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
Shape of A: (10, 10)

In [2]:
#B.

B = np.ones((5, 5), dtype=int)

print("B:\n", B)

print("Shape of B:", B.shape)
print("Size of B:", B.size)
print("Dimensions of B:", B.ndim)

#np.ones(): Creates a new array of given shape and type, filled with ones.
#(5, 5): Specifies the shape of the array to be created.
#dtype=int: Specifies the data type of the array elements as integers.

B:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape of B: (5, 5)
Size of B: 25
Dimensions of B: 2

In [3]:
#C.

C = np.arange(-5, 6)

C *= 2

print("C:", C)

#np.arange(-5, 6): Creates an array of values from -5 to +5.
#C *= 2: Multiplies each value in the array C by 2.
#print("C:", C): Prints the resulting array C.

C: [-10  -8  -6  -4  -2   0   2   4   6   8  10]

##Exercise 2

A. Choose the values from the range of numbers 1 to 100.
1. Create an array with 30 values within the range of numbers given. You can choose your own start value and stop value. However, the incrementing value will be 2.
   * Explain what is the result briefly by writing a comment before the code.
2. Multiply the resulting array with 3. Print the result.

In [4]:
#1.

#np.arange(10, 69, 2): Creates an array starting from 10, ending at 68, with an increment of 2. This results in an array with 30 values.

import numpy as np

arr = np.arange(10, 69, 2)

print("Array:", arr)

Array: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68]

In [5]:
#2.

arr *= 3

print("Modified Array:", arr)

Modified Array: [ 30  36  42  48  54  60  66  72  78  84  90  96 102 108 114 120 126 132
 138 144 150 156 162 168 174 180 186 192 198 204]

##Exercise 3

A. Create a four-dimensional array of random integers in the interval [0, 12]. Print the result.
1. Get the dimensions, shape, and size.
    * Explain what is the result briefly by writing a comment before the code.

B. Get the maximum number for each dimensions and display it.
   * Explain what is the result briefly by writing a comment before the code.

C. Multipy each array with 4. What is its result?
    * Write a brief explanation on the multiplication process.

In [6]:
#A.

#np.random.randint(0, 13, size=(2, 3, 4, 5)): Generates a four-dimensional array of random integers ranging from 0 to 12. The dimensions of the array are specified as (2, 3, 4, 5).

import numpy as np

four_dim_array = np.random.randint(0, 13, size=(2, 3, 4, 5))

print("Four-dimensional Array:\n", four_dim_array)

Four-dimensional Array:
 [[[[ 8  0  8  0 12]
   [ 7  0  4  2  2]
   [ 9 10  0  0  7]
   [ 8 10  6  6  2]]

  [[ 2  3  5 10  1]
   [12 10  7 12  6]
   [11 10  8  3  8]
   [ 2  5 11 12  4]]

  [[ 9  9  2 10  1]
   [12  1  2  1  2]
   [11 12 12  0  3]
   [ 7  4  4  8  4]]]


 [[[11  9 12  4  8]
   [ 8  5 12  0 11]
   [11 10  8 11  7]
   [ 5  0 10  9 10]]

  [[ 3  3  7  8  3]
   [ 4  5  0  9  4]
   [ 9  4 12  8 10]
   [ 7  8  1  3 10]]

  [[ 6 11  2 10 10]
   [12  9  8 12  8]
   [ 8  0  7  9  5]
   [ 5  2  3 10  3]]]]

In [7]:
#B.

#four_dim_array.max(axis=(0, 1, 2, 3)): Finds the maximum number along all axes (dimensions) of the four-dimensional array.

max_values = four_dim_array.max(axis=(0, 1, 2, 3))

print("Maximum number for each dimension:", max_values)

Maximum number for each dimension: 12

In [8]:
#C.

four_dim_array *= 4

print("Array after multiplication:\n", four_dim_array)

#four_dim_array *= 4: Multiplies each element in the four-dimensional array by 4. This operation scales the entire array by a factor of 4, increasing all values proportionally.

Array after multiplication:
 [[[[32  0 32  0 48]
   [28  0 16  8  8]
   [36 40  0  0 28]
   [32 40 24 24  8]]

  [[ 8 12 20 40  4]
   [48 40 28 48 24]
   [44 40 32 12 32]
   [ 8 20 44 48 16]]

  [[36 36  8 40  4]
   [48  4  8  4  8]
   [44 48 48  0 12]
   [28 16 16 32 16]]]


 [[[44 36 48 16 32]
   [32 20 48  0 44]
   [44 40 32 44 28]
   [20  0 40 36 40]]

  [[12 12 28 32 12]
   [16 20  0 36 16]
   [36 16 48 32 40]
   [28 32  4 12 40]]

  [[24 44  8 40 40]
   [48 36 32 48 32]
   [32  0 28 36 20]
   [20  8 12 40 12]]]]